// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b751ea84-8af0-4947-bf15-0bbb04a678a3",
    "aws_cognito_region": "us-west-2",
    "aws_mobile_analytics_app_id": "f001f22df5c648fcb53d97bdfd2daa15",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
